name: Drasi Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature-lib

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Hugo Website
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.152.2
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Setup Docsy
        run: |
          cd docs
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          cd themes/docsy
          npm install
      - name: Build Hugo Site
        run: |
          cd docs
          hugo --baseURL "https://ruokun-niu.github.io/docs/"
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
